[package]
name = "sqlite-regex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlite3-loadable = {path="../rust-sqlite-exts/sqlite3-loadable"}
sqlite3ext-sys = {path="../rust-sqlite-exts/sqlite3ext-sys"}
regex = "1"

[lib]
crate-type=["rlib", "cdylib"]
name = "regex0"